apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: canteen-app
spec:
  selector:
    app: server
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
